version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.7
    - 1.3.9
    - 1.4.1
    - 1.5.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.16
  - dependency-name: globby
    versions:
    - 11.0.2
  - dependency-name: markdown-it-anchor
    versions:
    - 6.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: inquirer
    versions:
    - 7.3.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
